//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.SpecialSpellTimer.resources.strings {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_EN() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.SpecialSpellTimer.resources.strings.Strings-EN", typeof(Strings_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Arcanist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ACN {
            get {
                return ResourceManager.GetString("ACN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in ACT.SpecialSpellTimer Assembly resolution. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ACTAssemblyError {
            get {
                return ResourceManager.GetString("ACTAssemblyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ActionHeader {
            get {
                return ResourceManager.GetString("ActionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Actor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ActorHeader {
            get {
                return ResourceManager.GetString("ActorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in the initialization of ACT.SpecialSpellTimer plug-ins. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ACTPluginStartError {
            get {
                return ResourceManager.GetString("ACTPluginStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred at the end of ACT.SpecialSpellTimer plug-ins. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ACTPluginStopError {
            get {
                return ResourceManager.GetString("ACTPluginStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add timers instead of restarting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddMessageCheckBox {
            get {
                return ResourceManager.GetString("AddMessageCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm and TTS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlarmTab {
            get {
                return ResourceManager.GetString("AlarmTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alchemist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ALC {
            get {
                return ResourceManager.GetString("ALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Off に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AllOffButton {
            get {
                return ResourceManager.GetString("AllOffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All On に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AllOnButton {
            get {
                return ResourceManager.GetString("AllOnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テロップを常に表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlwaysDisplayTelop {
            get {
                return ResourceManager.GetString("AlwaysDisplayTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analyze に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnalyzeCombat {
            get {
                return ResourceManager.GetString("AnalyzeCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ARC {
            get {
                return ResourceManager.GetString("ARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Armorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ARM {
            get {
                return ResourceManager.GetString("ARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Astrologian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AST {
            get {
                return ResourceManager.GetString("AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reverse sorting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoSortReverseCheckbox {
            get {
                return ResourceManager.GetString("AutoSortReverseCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alpha channel of the background color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BackgroundColorAlphaTitle {
            get {
                return ResourceManager.GetString("BackgroundColorAlphaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bar size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarSize {
            get {
                return ResourceManager.GetString("BarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black Mage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BLM {
            get {
                return ResourceManager.GetString("BLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Botanist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BOT {
            get {
                return ResourceManager.GetString("BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BRD {
            get {
                return ResourceManager.GetString("BRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blacksmith に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BSM {
            get {
                return ResourceManager.GetString("BSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buffer size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BufferSize {
            get {
                return ResourceManager.GetString("BufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background alpha... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeBackgroundAlpha {
            get {
                return ResourceManager.GetString("ChangeBackgroundAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background color... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeBackgroundColor {
            get {
                return ResourceManager.GetString("ChangeBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bar color... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeBarColor {
            get {
                return ResourceManager.GetString("ChangeBarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bar outline color... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeBarOutlineColor {
            get {
                return ResourceManager.GetString("ChangeBarOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right click to edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeByRightClicking {
            get {
                return ResourceManager.GetString("ChangeByRightClicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeFont {
            get {
                return ResourceManager.GetString("ChangeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font color... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeFontColor {
            get {
                return ResourceManager.GetString("ChangeFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font outline color... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeFontOutlineColor {
            get {
                return ResourceManager.GetString("ChangeFontOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClearAllButton {
            get {
                return ResourceManager.GetString("ClearAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click-through に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClickThrough {
            get {
                return ResourceManager.GetString("ClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conjurer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CNJ {
            get {
                return ResourceManager.GetString("CNJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combat Analyzer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CombatAnalyzerTabTitle {
            get {
                return ResourceManager.GetString("CombatAnalyzerTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analyzing the log... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CombatAnalyzing {
            get {
                return ResourceManager.GetString("CombatAnalyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable combat log analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CombatLogEnabledCheckBox {
            get {
                return ResourceManager.GetString("CombatLogEnabledCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comma &quot;,&quot; makes new line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommaLineBreakExplain {
            get {
                return ResourceManager.GetString("CommaLineBreakExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyLog {
            get {
                return ResourceManager.GetString("CopyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy log details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyLogDetail {
            get {
                return ResourceManager.GetString("CopyLogDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Carpenter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CRP {
            get {
                return ResourceManager.GetString("CRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Culinarian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CUL {
            get {
                return ResourceManager.GetString("CUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play sound after delay に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DelayedSoundEffect {
            get {
                return ResourceManager.GetString("DelayedSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play sound when log matches, after N seconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DelayedSoundEffectAfterMatch {
            get {
                return ResourceManager.GetString("DelayedSoundEffectAfterMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ Disabled when set to 0 (never hides) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisableWhenClear {
            get {
                return ResourceManager.GetString("DisableWhenClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Priority に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisplayOrderLabel {
            get {
                return ResourceManager.GetString("DisplayOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display progress bar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisplayRemainingTimeCheckBox {
            get {
                return ResourceManager.GetString("DisplayRemainingTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   seconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisplaySeconds {
            get {
                return ResourceManager.GetString("DisplaySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always show (even when completed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DontHideCheckBox {
            get {
                return ResourceManager.GetString("DontHideCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to download? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DownloadPrompt {
            get {
                return ResourceManager.GetString("DownloadPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dragoon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DRG {
            get {
                return ResourceManager.GetString("DRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark Knight に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DRK {
            get {
                return ResourceManager.GetString("DRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elapsed seconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ElapsedHeader {
            get {
                return ResourceManager.GetString("ElapsedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnabledSpellTimerNoDecimalCheckBox {
            get {
                return ResourceManager.GetString("EnabledSpellTimerNoDecimalCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide spell timers after completion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EraseAfterRecast {
            get {
                return ResourceManager.GetString("EraseAfterRecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extend beyond the original recast time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExtendBeyondOriginalRecastTimeCheckBox {
            get {
                return ResourceManager.GetString("ExtendBeyondOriginalRecastTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fisher に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FSH {
            get {
                return ResourceManager.GetString("FSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gladiator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GLD {
            get {
                return ResourceManager.GetString("GLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Goldsmith に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GSM {
            get {
                return ResourceManager.GetString("GSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HPHeader {
            get {
                return ResourceManager.GetString("HPHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play sound when log matches に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImmediateSoundEffect {
            get {
                return ResourceManager.GetString("ImmediateSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset to defaults に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitializationButton {
            get {
                return ResourceManager.GetString("InitializationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language (言語) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lancer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LNC {
            get {
                return ResourceManager.GetString("LNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load color scheme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadColorSet {
            get {
                return ResourceManager.GetString("LoadColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred by a load of a XML file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadXMLError {
            get {
                return ResourceManager.GetString("LoadXMLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogHeader {
            get {
                return ResourceManager.GetString("LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogTypeHeader {
            get {
                return ResourceManager.GetString("LogTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leatherworker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LTW {
            get {
                return ResourceManager.GetString("LTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This looks for partial matches in the game log\nExample)\r\nIf you chose &quot;freezing sword&quot; as your matching text.\nAnd the log contains the string &quot;Shiva uses stance of freezing sword&quot;.\n→ Then this would match that line in the game log. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MatchingKeywordExplanationTooltip {
            get {
                return ResourceManager.GetString("MatchingKeywordExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matching log text to show に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MatchingLogWordLabel {
            get {
                return ResourceManager.GetString("MatchingLogWordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matching log text for extending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MatchingLogWordToExpandLabel {
            get {
                return ResourceManager.GetString("MatchingLogWordToExpandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matching log text to hide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MatchingWordsToHide {
            get {
                return ResourceManager.GetString("MatchingWordsToHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delay before displaying に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MatchLogLabel {
            get {
                return ResourceManager.GetString("MatchLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machinist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MCH {
            get {
                return ResourceManager.GetString("MCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message to display on ticker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageOnTickerLabel {
            get {
                return ResourceManager.GetString("MessageOnTickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Millisecs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Millisecond {
            get {
                return ResourceManager.GetString("Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miner に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MIN {
            get {
                return ResourceManager.GetString("MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MNK {
            get {
                return ResourceManager.GetString("MNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Marauder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MRD {
            get {
                return ResourceManager.GetString("MRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Telop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewTelop {
            get {
                return ResourceManager.GetString("NewTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in the confirmation of updates: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewVersionError {
            get {
                return ResourceManager.GetString("NewVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New version of {0} has been released. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewVersionReleased {
            get {
                return ResourceManager.GetString("NewVersionReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ninja に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NIN {
            get {
                return ResourceManager.GetString("NIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumberHeader {
            get {
                return ResourceManager.GetString("NumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0: Transparent, 255: Opaque に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpacityDescription {
            get {
                return ResourceManager.GetString("OpacityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OptionTabPageTitle {
            get {
                return ResourceManager.GetString("OptionTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display overlay: OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OverlayDisplaySwitchIsOff {
            get {
                return ResourceManager.GetString("OverlayDisplaySwitchIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display overlay: ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OverlayDisplaySwitchIsOn {
            get {
                return ResourceManager.GetString("OverlayDisplaySwitchIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display overlay even if FFXIV is not running に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OverlayForceVisibleCheckBox {
            get {
                return ResourceManager.GetString("OverlayForceVisibleCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Panel name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PanelNameLabel {
            get {
                return ResourceManager.GetString("PanelNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ &lt;2&gt; - &lt;8&gt; can be used, however the order may be incorrect. (Requires restart) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartyMemberNumberExplainLabel {
            get {
                return ResourceManager.GetString("PartyMemberNumberExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use party member names in matching に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartyPronounLabel {
            get {
                return ResourceManager.GetString("PartyPronounLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ♪ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paladin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PLD {
            get {
                return ResourceManager.GetString("PLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PleaseWait1 {
            get {
                return ResourceManager.GetString("PleaseWait1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PleaseWait2 {
            get {
                return ResourceManager.GetString("PleaseWait2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait . . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PleaseWait3 {
            get {
                return ResourceManager.GetString("PleaseWait3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait . . . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PleaseWait4 {
            get {
                return ResourceManager.GetString("PleaseWait4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait . . . . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PleaseWait5 {
            get {
                return ResourceManager.GetString("PleaseWait5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ Smaller has more priority に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PriorityExplainLabel {
            get {
                return ResourceManager.GetString("PriorityExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progress bar appearance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressBarAppearance {
            get {
                return ResourceManager.GetString("ProgressBarAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pugilist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PUG {
            get {
                return ResourceManager.GetString("PUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play sound when timer expires に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RecastCompleteSoundEffect {
            get {
                return ResourceManager.GetString("RecastCompleteSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recast time (seconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RecastTimeLabel {
            get {
                return ResourceManager.GetString("RecastTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular expression matching is disabled by default.\nPrefer partial string matching instead of regular expressions for better performance. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegularExpressionExplanationTooltip {
            get {
                return ResourceManager.GetString("RegularExpressionExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RepeatCheckBox {
            get {
                return ResourceManager.GetString("RepeatCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ Requires restart に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequiresRestart {
            get {
                return ResourceManager.GetString("RequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to reset all settings and ticker positions? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResetAllPrompt {
            get {
                return ResourceManager.GetString("ResetAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply bar size to all spell timers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResetSpellBarSize {
            get {
                return ResourceManager.GetString("ResetSpellBarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply colors to all spell timers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResetSpellColor {
            get {
                return ResourceManager.GetString("ResetSpellColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply font to all spell timers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResetSpellFont {
            get {
                return ResourceManager.GetString("ResetSpellFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply color to all tickers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResetTelopColor {
            get {
                return ResourceManager.GetString("ResetTelopColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply font to all tickers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResetTelopFont {
            get {
                return ResourceManager.GetString("ResetTelopFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reverse direciton に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReverseDirectionCheckbox {
            get {
                return ResourceManager.GetString("ReverseDirectionCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rogue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ROG {
            get {
                return ResourceManager.GetString("ROG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample spell に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SampleSpell {
            get {
                return ResourceManager.GetString("SampleSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample ticker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SampleTelop {
            get {
                return ResourceManager.GetString("SampleTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save color scheme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveColorSet {
            get {
                return ResourceManager.GetString("SaveColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scholar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SCH {
            get {
                return ResourceManager.GetString("SCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screen update interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScreenUpdateTimeLabel {
            get {
                return ResourceManager.GetString("ScreenUpdateTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SecondsLabel {
            get {
                return ResourceManager.GetString("SecondsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seconds later に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SecondsLater {
            get {
                return ResourceManager.GetString("SecondsLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Job Filter... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectJobButton {
            get {
                return ResourceManager.GetString("SelectJobButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ If you want to limit the job of interest, please turn ON the check に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectJobSubtitle {
            get {
                return ResourceManager.GetString("SelectJobSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the job of interest に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectJobTitle {
            get {
                return ResourceManager.GetString("SelectJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zone Filter... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectZoneButton {
            get {
                return ResourceManager.GetString("SelectZoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select zones に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectZoneTitle {
            get {
                return ResourceManager.GetString("SelectZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set time zero to here に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetLogOrigin {
            get {
                return ResourceManager.GetString("SetLogOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show visual timer and progress bar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowProgressBarCheckBox {
            get {
                return ResourceManager.GetString("ShowProgressBarCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summoner に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMN {
            get {
                return ResourceManager.GetString("SMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort spell timers by next recast に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SortByRecastOrder {
            get {
                return ResourceManager.GetString("SortByRecastOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play sound before complete, before N seconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SoundEffectBeforeComplete {
            get {
                return ResourceManager.GetString("SoundEffectBeforeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in the regeneration of ACT.SpecialSpellTimer Sound. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SoundError {
            get {
                return ResourceManager.GetString("SoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delay until sound plays (in seconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SoundInSeconds {
            get {
                return ResourceManager.GetString("SoundInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Before seconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SoundInSecondsBefore {
            get {
                return ResourceManager.GetString("SoundInSecondsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Period に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpanHeader {
            get {
                return ResourceManager.GetString("SpanHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ▶ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpeakButton {
            get {
                return ResourceManager.GetString("SpeakButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ Please set according to your machine specs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecsLabel {
            get {
                return ResourceManager.GetString("SpecsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete all spell timers? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpellClearAllPrompt {
            get {
                return ResourceManager.GetString("SpellClearAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spell name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpellNameLabel {
            get {
                return ResourceManager.GetString("SpellNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ A performance of drawing improves. (Requires restart) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpellTimerFormatExplainLabel {
            get {
                return ResourceManager.GetString("SpellTimerFormatExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recast time of spell timers is indicated by an integer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpellTimerFormatLabel {
            get {
                return ResourceManager.GetString("SpellTimerFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in the Refresh of ACT.SpecialSpellTimer spell timer Window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpellTimerRefreshError {
            get {
                return ResourceManager.GetString("SpellTimerRefreshError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spell Timers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpellTimerTabTitle {
            get {
                return ResourceManager.GetString("SpellTimerTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SupeSupe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SupeSupe {
            get {
                return ResourceManager.GetString("SupeSupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display spell に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SwitchOverlayButton {
            get {
                return ResourceManager.GetString("SwitchOverlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete all tickers? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TelopClearAllPrompt {
            get {
                return ResourceManager.GetString("TelopClearAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display all tickers (for position adjustment): OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TelopDisplaySwitchIsOff {
            get {
                return ResourceManager.GetString("TelopDisplaySwitchIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display all tickers (for position adjustment): ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TelopDisplaySwitchIsOn {
            get {
                return ResourceManager.GetString("TelopDisplaySwitchIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For the displayed message, {COUNT} will be replaced by the number of seconds until the ticker completes.\n{COUNT} → displays a single decimal point (eg. 30.0)\n{COUNT0} → display no decimals (eg. 30) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TelopMessageExplanationTooltip {
            get {
                return ResourceManager.GetString("TelopMessageExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tickers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TelopTabPageTitle {
            get {
                return ResourceManager.GetString("TelopTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text to speak に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextToSpeakLabel {
            get {
                return ResourceManager.GetString("TextToSpeakLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thaumaturge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string THM {
            get {
                return ResourceManager.GetString("THM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ticker name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TickerName {
            get {
                return ResourceManager.GetString("TickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timestamp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimestampHeader {
            get {
                return ResourceManager.GetString("TimestampHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overlay opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TransmitOverlay {
            get {
                return ResourceManager.GetString("TransmitOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the spell name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateSpellNameTitle {
            get {
                return ResourceManager.GetString("UpdateSpellNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the panel name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateSpellPanelTitle {
            get {
                return ResourceManager.GetString("UpdateSpellPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the name of the ticker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateTelopNameTitle {
            get {
                return ResourceManager.GetString("UpdateTelopNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Regex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UseRegex {
            get {
                return ResourceManager.GetString("UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warrior に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WAR {
            get {
                return ResourceManager.GetString("WAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound effect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WaveSoundLabel {
            get {
                return ResourceManager.GetString("WaveSoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White Mage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WHM {
            get {
                return ResourceManager.GetString("WHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weaver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WVR {
            get {
                return ResourceManager.GetString("WVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML files (*.xml)|*.xml|All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlFileFilter {
            get {
                return ResourceManager.GetString("XmlFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
